import type { Metadata } from "next";
import { brand, contactDetails } from "@/config/siteConfig";
import LegalLayout, { type LegalSection as LegalSectionType } from "@/components/legal/LegalLayout";
import LegalSection from "@/components/legal/LegalSection";

export const metadata: Metadata = {
  title: "Privacy Policy | Magnolia Grove Consultants",
  description:
    "How Magnolia Grove Consultants, LLC collects, uses, and protects client and visitor data.",
};

const sections: LegalSectionType[] = [
  { id: "information-we-collect", label: "Information We Collect" },
  { id: "how-we-use-information", label: "How We Use Your Information" },
  { id: "third-party-processors", label: "Third-Party Service Providers" },
  { id: "confidentiality", label: "Confidentiality Standards" },
  { id: "data-security-retention", label: "Data Security & Retention" },
  { id: "your-rights", label: "Your Rights & Contact" },
];

export default function PrivacyPage() {
  const email = contactDetails.find((detail) => detail.label === "Email")?.value;

  return (
    <LegalLayout title="Privacy Policy" lastUpdated="July 27, 2026" sections={sections}>
      <LegalSection id="information-we-collect" index="01" title="Information We Collect">
        <p>
          {brand.name}, LLC (&quot;Magnolia Grove,&quot; &quot;we,&quot; &quot;us,&quot; or
          &quot;our&quot;) collects information you voluntarily submit through our intake and
          strategy session forms, including your name, email address, phone number, and organization
          or campaign details. We also collect standard technical data generated by your visit,
          including your IP address, browser type, device information, and general browsing metadata
          captured through normal web server operation.
        </p>
        <p>
          We do not collect sensitive personal information beyond what you voluntarily provide, and
          we do not use tracking methods intended to identify you outside the scope of evaluating
          and responding to your inquiry.
        </p>
      </LegalSection>

      <LegalSection id="how-we-use-information" index="02" title="How We Use Your Information">
        <p>Information submitted to us is used exclusively to:</p>
        <ul className="flex flex-col gap-2 pl-5">
          <li className="list-disc">
            Schedule and prepare for consultation and strategy sessions;
          </li>
          <li className="list-disc">
            Communicate with you regarding your project, engagement, or inquiry;
          </li>
          <li className="list-disc">
            Optimize our website, forms, and platform based on aggregate usage patterns; and
          </li>
          <li className="list-disc">
            Deliver campaign advisory, field, media, print, and digital services under an active
            engagement.
          </li>
        </ul>
        <p className="font-semibold text-white">
          We do not sell, rent, or share your information with third-party marketers under any
          circumstances.
        </p>
      </LegalSection>

      <LegalSection
        id="third-party-processors"
        index="03"
        title="Third-Party Service Providers & Infrastructure"
      >
        <p>
          To operate this website securely and reliably, submitted data may pass through the
          following infrastructure processors, each of which is contractually and technically
          restricted to processing data solely on our behalf:
        </p>
        <ul className="flex flex-col gap-2 pl-5">
          <li className="list-disc">
            <span className="font-semibold text-white">Vercel</span> — application hosting and
            content delivery infrastructure.
          </li>
          <li className="list-disc">
            <span className="font-semibold text-white">Resend</span> — transactional email routing
            used to deliver intake form notifications and confirmations.
          </li>
          <li className="list-disc">
            <span className="font-semibold text-white">Cloudflare Turnstile</span> — bot detection
            and spam prevention used to protect our forms from automated abuse.
          </li>
        </ul>
        <p>
          These providers do not have independent rights to use your information for their own
          purposes and are bound by their respective data processing terms.
        </p>
      </LegalSection>

      <LegalSection id="confidentiality" index="04" title="Confidentiality Standards">
        <p>
          All campaign strategy, client intelligence, and engagement details submitted to
          {` ${brand.name}`} are treated as strictly confidential. Access is limited internally to
          personnel directly involved in evaluating or delivering your engagement, and we do not
          disclose client identities, race details, or strategic materials to any outside party
          absent your written consent or a binding legal obligation.
        </p>
      </LegalSection>

      <LegalSection id="data-security-retention" index="05" title="Data Security & Retention">
        <p>
          We apply reasonable technical and organizational safeguards — including encrypted
          transmission, access-restricted storage, and vetted infrastructure processors — to protect
          submitted data against unauthorized access, alteration, or disclosure. We retain submitted
          information only as long as necessary to fulfill the purposes described in this policy, or
          as required to comply with legal, accounting, or reporting obligations.
        </p>
      </LegalSection>

      <LegalSection id="your-rights" index="06" title="Your Rights & Contact">
        <p>
          You may request access to, correction of, or deletion of your personal information at any
          time. To exercise these rights or ask a question about this policy, contact us at{" "}
          {email && (
            <a href={`mailto:${email}`} className="text-gold-bright hover:text-white">
              {email}
            </a>
          )}
          . We will respond to verified requests within a reasonable timeframe.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
